apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-http
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/component: http
    helm.sh/chart: {{ .Chart.Name }}
    helm.sh/chart-version: {{ .Chart.Version }}
data:
    default.conf: |
        server {
            listen 80 default_server;
            server_name _;
            root /app/public;
            index index.html index.htm index.php;
            charset utf-8;

            location = /favicon.ico { log_not_found off; access_log off; }
            location = /robots.txt  { log_not_found off; access_log off; }

            client_max_body_size 25M;

            error_page 404 /index.php;

            location / {
                try_files $uri /index.php$is_args$args;
            }

            location ~ \.php$ {
                add_header X-Served-By FWD;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_pass {{ .Release.Name }}-app:9000;
            }

            location ~ /\.ht {
                deny all;
            }
        }
